[package]
name = "SafforaOS"
version = "0.1.0"
authors = ["Kenneth Harmer chase.harmer@yahoo.com"]
edition = "2018"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = []